### ISSUE TITLE
Entwickle eine Spieleidee

### ISSUE THREAD

**Issue by klaus31** [klaus31/format-my-shoe#3]

**Comment by klaus31** [comment]
Ich mag ein Punkte-Game ala "Candy Crush" oder "Dots"

**Comment by klaus31** [comment]
Ein schönes Alkoholiker-Game finde ich auch gut. Wir könnten das Bier zum Aufsammeln machen. Und dann gibt's noch Korn und Wein.
Statt Punkte gibt es eine Promille-Anzeige und die Steuerung wird immer besoffener.

Außerdem gibt es auch Wassergläser - die darf man nicht aufsammeln. Dann geht die Promille-Anzeige wieder runter und der Held nimmt schaden.

**Comment by perishedde** [comment]
**Ansatz 1**
* Bierkrüge austrinken
* Flaschen austrinken
* Fässer austrinken
* Dafür Punkte kriegen
* Startzustand: 3 Leben

**Spielidee Pseudo-Code**
```java
if (zuSchnellGetrunken && zuVielGetrunken) {
    sichÜbergeben();
    decreaseLebenCounter();
    punktAbzug();
} else {
    if (allesAusgetrunken) {
        eintragInDieHighscores();
    }
}
```
